'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BallotboxDashboard

    '''<summary>
    '''litUserId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litUserId As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litLocation As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lnkStateParked control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkStateParked As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''litStateParked control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litStateParked As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lnkStateInTransit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkStateInTransit As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''litStateInTransit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litStateInTransit As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lnkMyStockParked control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkMyStockParked As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''litMyStockParked control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litMyStockParked As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lnkInward control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkInward As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''litInward control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litInward As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lnkOutward control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkOutward As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''litOutward control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litOutward As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litErrorMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litErrorMessage As Global.System.Web.UI.WebControls.Literal
End Class
