'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditMaster

    '''<summary>
    '''lblTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''dvPri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvPri As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblElectionFor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblElectionFor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblrbUnitType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblrbUnitType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hidden_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidden_id As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidden_itemType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidden_itemType As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidden_itemFor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidden_itemFor As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidden_itemSpecification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidden_itemSpecification As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ItemName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ItemName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ItemDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ItemDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ItemNameLocal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ItemNameLocal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ItemDescriptionLocal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ItemDescriptionLocal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''alert_div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents alert_div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lbl_alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''submitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents submitButton As Global.System.Web.UI.WebControls.Button
End Class
