'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class index

    '''<summary>
    '''Dashboard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dashboard As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CntEvm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CntEvm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EVM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EVM As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CntBB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CntBB As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BallotBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BallotBox As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CntVvpat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CntVvpat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VVPAT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VVPAT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CntStnry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CntStnry As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''StationaryItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StationaryItems As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CntForms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CntForms As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Forms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Forms As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEvmUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEvmUnits As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEvmUnitsdesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEvmUnitsdesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblControlUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblControlUnits As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCu As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBallotUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBallotUnits As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBU As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVVPatUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVVPatUnits As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVvpat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVvpat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBallotBoxes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBallotBoxes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBB As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBallotBoxesDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBallotBoxesDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStationeryItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStationeryItems As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStnry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStnry As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStationeryItemsDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStationeryItemsDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStationeryItems1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStationeryItems1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStationeryItems2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStationeryItems2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStationeryItems3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStationeryItems3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStationeryItems4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStationeryItems4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStationeryItems5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStationeryItems5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStationeryItems6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStationeryItems6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStationeryItems7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStationeryItems7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBallotBoxes1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBallotBoxes1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFormsPRI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFormsPRI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFormPRI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFormPRI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFormsPRIDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFormsPRIDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFormsUlb1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFormsUlb1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFormULB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFormULB As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFormsUlb1Desc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFormsUlb1Desc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFormsUlb2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFormsUlb2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFormMC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFormMC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFormsUlb2Desc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFormsUlb2Desc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModTitle As Global.System.Web.UI.WebControls.Label
End Class
