'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class login

    '''<summary>
    '''ddllang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddllang As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''loginform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loginform As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblheader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblheader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''sm1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sm1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''up1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents up1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtUserID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUserID As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''rfvUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvUserName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtUserPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUserPass As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''rfvUserPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvUserPassword As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''upCaptcha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upCaptcha As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''SearchCaptcha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchCaptcha As Global.MSCaptcha.CaptchaControl

    '''<summary>
    '''txtCaptcha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCaptcha As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtbchangeCaptcha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtbchangeCaptcha As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLogin As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hidHash control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidHash As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''recoverform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents recoverform As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''upRecoverForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upRecoverForm As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblRecoverPwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecoverPwd As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvFP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvFP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtID As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lbl_msg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_msg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvOtpBtns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvOtpBtns As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnSendOTP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSendOTP As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''dvOTP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvOTP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtOTP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOTP As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnResendOTP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResendOTP As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbl_otp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_otp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnConfirmOTP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmOTP As Global.System.Web.UI.WebControls.Button
End Class
