'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.Resource", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inventory Managment Information System.
        '''</summary>
        Friend Shared ReadOnly Property AboutApplication() As String
            Get
                Return ResourceManager.GetString("AboutApplication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About Us.
        '''</summary>
        Friend Shared ReadOnly Property AboutUs() As String
            Get
                Return ResourceManager.GetString("AboutUs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Annexure-I Not Available.
        '''</summary>
        Friend Shared ReadOnly Property AnnexureUnavailable() As String
            Get
                Return ResourceManager.GetString("AnnexureUnavailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inventory Managment Information System.
        '''</summary>
        Friend Shared ReadOnly Property ApplicationName() As String
            Get
                Return ResourceManager.GetString("ApplicationName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to April.
        '''</summary>
        Friend Shared ReadOnly Property Apr() As String
            Get
                Return ResourceManager.GetString("Apr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4.
        '''</summary>
        Friend Shared ReadOnly Property Apr1() As String
            Get
                Return ResourceManager.GetString("Apr1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to August.
        '''</summary>
        Friend Shared ReadOnly Property Aug() As String
            Get
                Return ResourceManager.GetString("Aug", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 8.
        '''</summary>
        Friend Shared ReadOnly Property Aug1() As String
            Get
                Return ResourceManager.GetString("Aug1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Back To Login.
        '''</summary>
        Friend Shared ReadOnly Property BackToLogin() As String
            Get
                Return ResourceManager.GetString("BackToLogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ballot Box.
        '''</summary>
        Friend Shared ReadOnly Property BallotBox() As String
            Get
                Return ResourceManager.GetString("BallotBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ballot Unit.
        '''</summary>
        Friend Shared ReadOnly Property BallotUnit() As String
            Get
                Return ResourceManager.GetString("BallotUnit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Panchayat Samiti.
        '''</summary>
        Friend Shared ReadOnly Property Blk() As String
            Get
                Return ResourceManager.GetString("Blk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property btnCancel() As String
            Get
                Return ResourceManager.GetString("btnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend Shared ReadOnly Property btnSave() As String
            Get
                Return ResourceManager.GetString("btnSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Submit.
        '''</summary>
        Friend Shared ReadOnly Property btnSubmit() As String
            Get
                Return ResourceManager.GetString("btnSubmit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verify.
        '''</summary>
        Friend Shared ReadOnly Property btnVerify() As String
            Get
                Return ResourceManager.GetString("btnVerify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add New Stock.
        '''</summary>
        Friend Shared ReadOnly Property btn_add_new() As String
            Get
                Return ResourceManager.GetString("btn_add_new", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirm OTP.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmOTP() As String
            Get
                Return ResourceManager.GetString("ConfirmOTP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Armsdale Building, HP Secretariat, Chotta Shimla (HP)- 171002.
        '''</summary>
        Friend Shared ReadOnly Property ContactAddress() As String
            Get
                Return ResourceManager.GetString("ContactAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to secysec-hp[at]nic[dot]in.
        '''</summary>
        Friend Shared ReadOnly Property ContactEmail() As String
            Get
                Return ResourceManager.GetString("ContactEmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Fax)  : 2620152.
        '''</summary>
        Friend Shared ReadOnly Property ContactFax() As String
            Get
                Return ResourceManager.GetString("ContactFax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Office): 0177-2620152.
        '''</summary>
        Friend Shared ReadOnly Property ContactPhone() As String
            Get
                Return ResourceManager.GetString("ContactPhone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact.
        '''</summary>
        Friend Shared ReadOnly Property ContactUs() As String
            Get
                Return ResourceManager.GetString("ContactUs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contro lUnit.
        '''</summary>
        Friend Shared ReadOnly Property ControlUnit() As String
            Get
                Return ResourceManager.GetString("ControlUnit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deactivate.
        '''</summary>
        Friend Shared ReadOnly Property DeActivateStockMaster() As String
            Get
                Return ResourceManager.GetString("DeActivateStockMaster", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to December.
        '''</summary>
        Friend Shared ReadOnly Property Dec() As String
            Get
                Return ResourceManager.GetString("Dec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 12.
        '''</summary>
        Friend Shared ReadOnly Property Dec1() As String
            Get
                Return ResourceManager.GetString("Dec1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zila.
        '''</summary>
        Friend Shared ReadOnly Property Dis() As String
            Get
                Return ResourceManager.GetString("Dis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Disclaimer.
        '''</summary>
        Friend Shared ReadOnly Property Disclaimer() As String
            Get
                Return ResourceManager.GetString("Disclaimer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Web Application, Inventory Managment Information System, has been developed for the State Election Commission, Himachal Pradesh by NIC Himachal Pradesh State Centre, Shimla. For any query/clarification, please get in touch with the respective District Panchayat Officer of your District. Any complaint or query requiring intervention of the State Election Commissioner may be routed through the concerned Deputy Commissioner..
        '''</summary>
        Friend Shared ReadOnly Property DisclaimerText() As String
            Get
                Return ResourceManager.GetString("DisclaimerText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download.
        '''</summary>
        Friend Shared ReadOnly Property Download() As String
            Get
                Return ResourceManager.GetString("Download", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Election Commission of India.
        '''</summary>
        Friend Shared ReadOnly Property ECI() As String
            Get
                Return ResourceManager.GetString("ECI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to National Voter&apos;s Service Portal.
        '''</summary>
        Friend Shared ReadOnly Property ECI_Search() As String
            Get
                Return ResourceManager.GetString("ECI_Search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Election Type.
        '''</summary>
        Friend Shared ReadOnly Property ElectionType() As String
            Get
                Return ResourceManager.GetString("ElectionType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Electoral Roll Management System.
        '''</summary>
        Friend Shared ReadOnly Property ERMS() As String
            Get
                Return ResourceManager.GetString("ERMS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search Electoral Roll.
        '''</summary>
        Friend Shared ReadOnly Property ERMS_Search() As String
            Get
                Return ResourceManager.GetString("ERMS_Search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter No. of Male and Female Electors.
        '''</summary>
        Friend Shared ReadOnly Property errElectors() As String
            Get
                Return ResourceManager.GetString("errElectors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Election Program Found.
        '''</summary>
        Friend Shared ReadOnly Property errNoElectionProgram() As String
            Get
                Return ResourceManager.GetString("errNoElectionProgram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export to Excel.
        '''</summary>
        Friend Shared ReadOnly Property ExportExcel() As String
            Get
                Return ResourceManager.GetString("ExportExcel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to February.
        '''</summary>
        Friend Shared ReadOnly Property Feb() As String
            Get
                Return ResourceManager.GetString("Feb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property Feb1() As String
            Get
                Return ResourceManager.GetString("Feb1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Forgot Password?.
        '''</summary>
        Friend Shared ReadOnly Property ForgetPasswordResource() As String
            Get
                Return ResourceManager.GetString("ForgetPasswordResource", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter your User ID below to reset your password.
        '''</summary>
        Friend Shared ReadOnly Property ForgetPasswordTitle() As String
            Get
                Return ResourceManager.GetString("ForgetPasswordTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Go.
        '''</summary>
        Friend Shared ReadOnly Property GoText() As String
            Get
                Return ResourceManager.GetString("GoText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Himachal Pradesh.
        '''</summary>
        Friend Shared ReadOnly Property HP() As String
            Get
                Return ResourceManager.GetString("HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Govt of Himachal Pradesh, India.
        '''</summary>
        Friend Shared ReadOnly Property hpgovt() As String
            Get
                Return ResourceManager.GetString("hpgovt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to January.
        '''</summary>
        Friend Shared ReadOnly Property Jan() As String
            Get
                Return ResourceManager.GetString("Jan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1.
        '''</summary>
        Friend Shared ReadOnly Property Jan1() As String
            Get
                Return ResourceManager.GetString("Jan1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to July.
        '''</summary>
        Friend Shared ReadOnly Property Jul() As String
            Get
                Return ResourceManager.GetString("Jul", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 7.
        '''</summary>
        Friend Shared ReadOnly Property Jul1() As String
            Get
                Return ResourceManager.GetString("Jul1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to June.
        '''</summary>
        Friend Shared ReadOnly Property Jun() As String
            Get
                Return ResourceManager.GetString("Jun", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 6.
        '''</summary>
        Friend Shared ReadOnly Property Jun1() As String
            Get
                Return ResourceManager.GetString("Jun1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to delete?.
        '''</summary>
        Friend Shared ReadOnly Property lblConfirmDelete() As String
            Get
                Return ResourceManager.GetString("lblConfirmDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Female.
        '''</summary>
        Friend Shared ReadOnly Property lblFemale() As String
            Get
                Return ResourceManager.GetString("lblFemale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Headquarter.
        '''</summary>
        Friend Shared ReadOnly Property lblHq() As String
            Get
                Return ResourceManager.GetString("lblHq", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to List of Ballot Boxes.
        '''</summary>
        Friend Shared ReadOnly Property lblListBallotBox() As String
            Get
                Return ResourceManager.GetString("lblListBallotBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to List of EVM Ballot Units.
        '''</summary>
        Friend Shared ReadOnly Property lblListBU() As String
            Get
                Return ResourceManager.GetString("lblListBU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to List of EVM Control Units.
        '''</summary>
        Friend Shared ReadOnly Property lblListCU() As String
            Get
                Return ResourceManager.GetString("lblListCU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to List of EVMs.
        '''</summary>
        Friend Shared ReadOnly Property lblListEVM() As String
            Get
                Return ResourceManager.GetString("lblListEVM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to List of Units Pending for QR Code Generation.
        '''</summary>
        Friend Shared ReadOnly Property lblListEVMPendingQR() As String
            Get
                Return ResourceManager.GetString("lblListEVMPendingQR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to List of EVMs FLC (First Level Check) in District.
        '''</summary>
        Friend Shared ReadOnly Property lblListFLC() As String
            Get
                Return ResourceManager.GetString("lblListFLC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to List of Stock and stationery.
        '''</summary>
        Friend Shared ReadOnly Property lblListStationary() As String
            Get
                Return ResourceManager.GetString("lblListStationary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Male.
        '''</summary>
        Friend Shared ReadOnly Property lblMale() As String
            Get
                Return ResourceManager.GetString("lblMale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Municipal Corporation.
        '''</summary>
        Friend Shared ReadOnly Property lblMC() As String
            Get
                Return ResourceManager.GetString("lblMC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Municipal Corporation Ward.
        '''</summary>
        Friend Shared ReadOnly Property lblMCWard() As String
            Get
                Return ResourceManager.GetString("lblMCWard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not Assigned.
        '''</summary>
        Friend Shared ReadOnly Property lblNA() As String
            Get
                Return ResourceManager.GetString("lblNA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name (In English).
        '''</summary>
        Friend Shared ReadOnly Property lblNameEn() As String
            Get
                Return ResourceManager.GetString("lblNameEn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name (In Hindi).
        '''</summary>
        Friend Shared ReadOnly Property lblNameHi() As String
            Get
                Return ResourceManager.GetString("lblNameHi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No.
        '''</summary>
        Friend Shared ReadOnly Property lblNo() As String
            Get
                Return ResourceManager.GetString("lblNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Other.
        '''</summary>
        Friend Shared ReadOnly Property lblOther() As String
            Get
                Return ResourceManager.GetString("lblOther", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gram Panchayat.
        '''</summary>
        Friend Shared ReadOnly Property lblPanchayat() As String
            Get
                Return ResourceManager.GetString("lblPanchayat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Panchayat Samiti.
        '''</summary>
        Friend Shared ReadOnly Property lblPanchSamiti() As String
            Get
                Return ResourceManager.GetString("lblPanchSamiti", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Polling Station.
        '''</summary>
        Friend Shared ReadOnly Property lblPollStation() As String
            Get
                Return ResourceManager.GetString("lblPollStation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to % Polled/Total- .
        '''</summary>
        Friend Shared ReadOnly Property lblPollTotal() As String
            Get
                Return ResourceManager.GetString("lblPollTotal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pradhan.
        '''</summary>
        Friend Shared ReadOnly Property lblPradhan() As String
            Get
                Return ResourceManager.GetString("lblPradhan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Panchayat Samiti Ward.
        '''</summary>
        Friend Shared ReadOnly Property lblPSWard() As String
            Get
                Return ResourceManager.GetString("lblPSWard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to State.
        '''</summary>
        Friend Shared ReadOnly Property lblState() As String
            Get
                Return ResourceManager.GetString("lblState", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Himachal Pradesh.
        '''</summary>
        Friend Shared ReadOnly Property lblStateName() As String
            Get
                Return ResourceManager.GetString("lblStateName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Urban Local Body.
        '''</summary>
        Friend Shared ReadOnly Property lblULB() As String
            Get
                Return ResourceManager.GetString("lblULB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Up Pradhan.
        '''</summary>
        Friend Shared ReadOnly Property lblUpPradhan() As String
            Get
                Return ResourceManager.GetString("lblUpPradhan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ward.
        '''</summary>
        Friend Shared ReadOnly Property lblWard() As String
            Get
                Return ResourceManager.GetString("lblWard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Panchayat Ward Member.
        '''</summary>
        Friend Shared ReadOnly Property lblWmGp() As String
            Get
                Return ResourceManager.GetString("lblWmGp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MC Ward Member.
        '''</summary>
        Friend Shared ReadOnly Property lblWmMc() As String
            Get
                Return ResourceManager.GetString("lblWmMc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ULB Ward Member.
        '''</summary>
        Friend Shared ReadOnly Property lblWmUlb() As String
            Get
                Return ResourceManager.GetString("lblWmUlb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Yes.
        '''</summary>
        Friend Shared ReadOnly Property lblYes() As String
            Get
                Return ResourceManager.GetString("lblYes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zila Parishad.
        '''</summary>
        Friend Shared ReadOnly Property lblZilaParishad() As String
            Get
                Return ResourceManager.GetString("lblZilaParishad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zila Parishad Ward.
        '''</summary>
        Friend Shared ReadOnly Property lblZPWard() As String
            Get
                Return ResourceManager.GetString("lblZPWard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add New.
        '''</summary>
        Friend Shared ReadOnly Property lnkAdd() As String
            Get
                Return ResourceManager.GetString("lnkAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Friend Shared ReadOnly Property lnkDelete() As String
            Get
                Return ResourceManager.GetString("lnkDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit.
        '''</summary>
        Friend Shared ReadOnly Property lnkEdit() As String
            Get
                Return ResourceManager.GetString("lnkEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to QR Code.
        '''</summary>
        Friend Shared ReadOnly Property lnkQR() As String
            Get
                Return ResourceManager.GetString("lnkQR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to March.
        '''</summary>
        Friend Shared ReadOnly Property Mar() As String
            Get
                Return ResourceManager.GetString("Mar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.
        '''</summary>
        Friend Shared ReadOnly Property Mar1() As String
            Get
                Return ResourceManager.GetString("Mar1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to May.
        '''</summary>
        Friend Shared ReadOnly Property May() As String
            Get
                Return ResourceManager.GetString("May", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 5.
        '''</summary>
        Friend Shared ReadOnly Property May1() As String
            Get
                Return ResourceManager.GetString("May1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Municipal Corporation.
        '''</summary>
        Friend Shared ReadOnly Property Mc() As String
            Get
                Return ResourceManager.GetString("Mc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to My Ballot Boxes.
        '''</summary>
        Friend Shared ReadOnly Property menuAddBallot() As String
            Get
                Return ResourceManager.GetString("menuAddBallot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add EVM.
        '''</summary>
        Friend Shared ReadOnly Property menuAddEVM() As String
            Get
                Return ResourceManager.GetString("menuAddEVM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add Items.
        '''</summary>
        Friend Shared ReadOnly Property menuAddStationary() As String
            Get
                Return ResourceManager.GetString("menuAddStationary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add EVM Warehouse.
        '''</summary>
        Friend Shared ReadOnly Property menuAddStore() As String
            Get
                Return ResourceManager.GetString("menuAddStore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allocate EVM Unit.
        '''</summary>
        Friend Shared ReadOnly Property menuAllocateEVM() As String
            Get
                Return ResourceManager.GetString("menuAllocateEVM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allocate.
        '''</summary>
        Friend Shared ReadOnly Property menuAllocateStationery() As String
            Get
                Return ResourceManager.GetString("menuAllocateStationery", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Application Management.
        '''</summary>
        Friend Shared ReadOnly Property menuApplicationManagement() As String
            Get
                Return ResourceManager.GetString("menuApplicationManagement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allocate.
        '''</summary>
        Friend Shared ReadOnly Property menuBallotBoxAllocation() As String
            Get
                Return ResourceManager.GetString("menuBallotBoxAllocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ballot Box Dashboard.
        '''</summary>
        Friend Shared ReadOnly Property menuBallotBoxDashboard() As String
            Get
                Return ResourceManager.GetString("menuBallotBoxDashboard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ballot Box.
        '''</summary>
        Friend Shared ReadOnly Property menuBallotHeader() As String
            Get
                Return ResourceManager.GetString("menuBallotHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unit Summary.
        '''</summary>
        Friend Shared ReadOnly Property menuBBSummary() As String
            Get
                Return ResourceManager.GetString("menuBBSummary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unit List.
        '''</summary>
        Friend Shared ReadOnly Property menuBBUnitList() As String
            Get
                Return ResourceManager.GetString("menuBBUnitList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Block Master.
        '''</summary>
        Friend Shared ReadOnly Property menuBlockMaster() As String
            Get
                Return ResourceManager.GetString("menuBlockMaster", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change Password.
        '''</summary>
        Friend Shared ReadOnly Property menuChangePassword() As String
            Get
                Return ResourceManager.GetString("menuChangePassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Friend Shared ReadOnly Property menuClose() As String
            Get
                Return ResourceManager.GetString("menuClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update Consumption.
        '''</summary>
        Friend Shared ReadOnly Property menuConsumedStationery() As String
            Get
                Return ResourceManager.GetString("menuConsumedStationery", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dashboard.
        '''</summary>
        Friend Shared ReadOnly Property menuDashboard() As String
            Get
                Return ResourceManager.GetString("menuDashboard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data Management.
        '''</summary>
        Friend Shared ReadOnly Property menuDataEntry() As String
            Get
                Return ResourceManager.GetString("menuDataEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data Entry Status.
        '''</summary>
        Friend Shared ReadOnly Property menuDataEntryStatus() As String
            Get
                Return ResourceManager.GetString("menuDataEntryStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mark Disposed.
        '''</summary>
        Friend Shared ReadOnly Property menuDisposeStationery() As String
            Get
                Return ResourceManager.GetString("menuDisposeStationery", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to District Master.
        '''</summary>
        Friend Shared ReadOnly Property menuDistrictMaster() As String
            Get
                Return ResourceManager.GetString("menuDistrictMaster", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allocate EVM Units.
        '''</summary>
        Friend Shared ReadOnly Property menuEVMAllocation() As String
            Get
                Return ResourceManager.GetString("menuEVMAllocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVM.
        '''</summary>
        Friend Shared ReadOnly Property menuEVMHeader() As String
            Get
                Return ResourceManager.GetString("menuEVMHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVM Unit List.
        '''</summary>
        Friend Shared ReadOnly Property menuEVMList() As String
            Get
                Return ResourceManager.GetString("menuEVMList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVM Unit Wise Summary.
        '''</summary>
        Friend Shared ReadOnly Property menuEVMSummary() As String
            Get
                Return ResourceManager.GetString("menuEVMSummary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generate QR Code.
        '''</summary>
        Friend Shared ReadOnly Property menuGenerateQR() As String
            Get
                Return ResourceManager.GetString("menuGenerateQR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Home.
        '''</summary>
        Friend Shared ReadOnly Property menuHome() As String
            Get
                Return ResourceManager.GetString("menuHome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Log In.
        '''</summary>
        Friend Shared ReadOnly Property menuLogin() As String
            Get
                Return ResourceManager.GetString("menuLogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Logout.
        '''</summary>
        Friend Shared ReadOnly Property menuLogout() As String
            Get
                Return ResourceManager.GetString("menuLogout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVM Tracking Mobile App.
        '''</summary>
        Friend Shared ReadOnly Property menuMobileApp() As String
            Get
                Return ResourceManager.GetString("menuMobileApp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to My Profile.
        '''</summary>
        Friend Shared ReadOnly Property menuMyProfile() As String
            Get
                Return ResourceManager.GetString("menuMyProfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nomination.
        '''</summary>
        Friend Shared ReadOnly Property menuNomination() As String
            Get
                Return ResourceManager.GetString("menuNomination", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nagar Nigam.
        '''</summary>
        Friend Shared ReadOnly Property menuNomSummaryMc() As String
            Get
                Return ResourceManager.GetString("menuNomSummaryMc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nagar Panchayat.
        '''</summary>
        Friend Shared ReadOnly Property menuNomSummaryUlb() As String
            Get
                Return ResourceManager.GetString("menuNomSummaryUlb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Panchayat Ward Master.
        '''</summary>
        Friend Shared ReadOnly Property menuPanWardMaster() As String
            Get
                Return ResourceManager.GetString("menuPanWardMaster", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gram Panchayat.
        '''</summary>
        Friend Shared ReadOnly Property menuPollResultsGp() As String
            Get
                Return ResourceManager.GetString("menuPollResultsGp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Panchayat Samiti.
        '''</summary>
        Friend Shared ReadOnly Property menuPollResultsPs() As String
            Get
                Return ResourceManager.GetString("menuPollResultsPs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zila Parishad.
        '''</summary>
        Friend Shared ReadOnly Property menuPollResultsZp() As String
            Get
                Return ResourceManager.GetString("menuPollResultsZp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print QR Code.
        '''</summary>
        Friend Shared ReadOnly Property menuPrintQR() As String
            Get
                Return ResourceManager.GetString("menuPrintQR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reports.
        '''</summary>
        Friend Shared ReadOnly Property menuReports() As String
            Get
                Return ResourceManager.GetString("menuReports", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Elected Representatives.
        '''</summary>
        Friend Shared ReadOnly Property menuRepresentatives() As String
            Get
                Return ResourceManager.GetString("menuRepresentatives", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reservation Status.
        '''</summary>
        Friend Shared ReadOnly Property menuReservationStatus() As String
            Get
                Return ResourceManager.GetString("menuReservationStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gram Panchayat/ULBs.
        '''</summary>
        Friend Shared ReadOnly Property menuReservationStatusGP() As String
            Get
                Return ResourceManager.GetString("menuReservationStatusGP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MC Wards Reservation.
        '''</summary>
        Friend Shared ReadOnly Property menuReservationStatusMC() As String
            Get
                Return ResourceManager.GetString("menuReservationStatusMC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zila Parishad/Panchayat Samiti.
        '''</summary>
        Friend Shared ReadOnly Property menuReservationStatusZPPS() As String
            Get
                Return ResourceManager.GetString("menuReservationStatusZPPS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rural.
        '''</summary>
        Friend Shared ReadOnly Property menuRural() As String
            Get
                Return ResourceManager.GetString("menuRural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stock and stationery.
        '''</summary>
        Friend Shared ReadOnly Property menuStationaryHeader() As String
            Get
                Return ResourceManager.GetString("menuStationaryHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Summary.
        '''</summary>
        Friend Shared ReadOnly Property menuStationaryStockSummary() As String
            Get
                Return ResourceManager.GetString("menuStationaryStockSummary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ULB Wards Reservation.
        '''</summary>
        Friend Shared ReadOnly Property menuUlbWardRes() As String
            Get
                Return ResourceManager.GetString("menuUlbWardRes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update FLC Details.
        '''</summary>
        Friend Shared ReadOnly Property menuUpdateFLC() As String
            Get
                Return ResourceManager.GetString("menuUpdateFLC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update.
        '''</summary>
        Friend Shared ReadOnly Property menuUpdateStationeryStock() As String
            Get
                Return ResourceManager.GetString("menuUpdateStationeryStock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add / Modify Items.
        '''</summary>
        Friend Shared ReadOnly Property menuUpdateStock() As String
            Get
                Return ResourceManager.GetString("menuUpdateStock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Urban.
        '''</summary>
        Friend Shared ReadOnly Property menuUrban() As String
            Get
                Return ResourceManager.GetString("menuUrban", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to View FLC Details.
        '''</summary>
        Friend Shared ReadOnly Property menuViewFLC() As String
            Get
                Return ResourceManager.GetString("menuViewFLC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to View Warehouse.
        '''</summary>
        Friend Shared ReadOnly Property menuViewWarehouse() As String
            Get
                Return ResourceManager.GetString("menuViewWarehouse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. Of Polling Stations.
        '''</summary>
        Friend Shared ReadOnly Property noOfPollStations() As String
            Get
                Return ResourceManager.GetString("noOfPollStations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. Of Wards.
        '''</summary>
        Friend Shared ReadOnly Property noOfWards() As String
            Get
                Return ResourceManager.GetString("noOfWards", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to November.
        '''</summary>
        Friend Shared ReadOnly Property Nov() As String
            Get
                Return ResourceManager.GetString("Nov", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11.
        '''</summary>
        Friend Shared ReadOnly Property Nov1() As String
            Get
                Return ResourceManager.GetString("Nov1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to October.
        '''</summary>
        Friend Shared ReadOnly Property Oct() As String
            Get
                Return ResourceManager.GetString("Oct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10.
        '''</summary>
        Friend Shared ReadOnly Property Oct1() As String
            Get
                Return ResourceManager.GetString("Oct1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Panchayat Samiti:.
        '''</summary>
        Friend Shared ReadOnly Property ofBlk() As String
            Get
                Return ResourceManager.GetString("ofBlk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zila:.
        '''</summary>
        Friend Shared ReadOnly Property ofDis() As String
            Get
                Return ResourceManager.GetString("ofDis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MC:.
        '''</summary>
        Friend Shared ReadOnly Property ofMC() As String
            Get
                Return ResourceManager.GetString("ofMC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gram Panchayat:.
        '''</summary>
        Friend Shared ReadOnly Property ofPanch() As String
            Get
                Return ResourceManager.GetString("ofPanch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ULB:.
        '''</summary>
        Friend Shared ReadOnly Property ofULB() As String
            Get
                Return ResourceManager.GetString("ofULB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ZP Ward:.
        '''</summary>
        Friend Shared ReadOnly Property ofZPWard() As String
            Get
                Return ResourceManager.GetString("ofZPWard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inventory MIS State Election Commission, Himachal Pradesh.
        '''</summary>
        Friend Shared ReadOnly Property PageResource1() As String
            Get
                Return ResourceManager.GetString("PageResource1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poll Date.
        '''</summary>
        Friend Shared ReadOnly Property PollDay() As String
            Get
                Return ResourceManager.GetString("PollDay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PRI Term.
        '''</summary>
        Friend Shared ReadOnly Property PriTerm() As String
            Get
                Return ResourceManager.GetString("PriTerm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Re-Activate.
        '''</summary>
        Friend Shared ReadOnly Property ReActivateStockMaster() As String
            Get
                Return ResourceManager.GetString("ReActivateStockMaster", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Related Links.
        '''</summary>
        Friend Shared ReadOnly Property RelatedLinks() As String
            Get
                Return ResourceManager.GetString("RelatedLinks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to State Election Commission, Himachal Pradesh.
        '''</summary>
        Friend Shared ReadOnly Property SEC() As String
            Get
                Return ResourceManager.GetString("SEC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to State Election Commission HP.
        '''</summary>
        Friend Shared ReadOnly Property SECHP() As String
            Get
                Return ResourceManager.GetString("SECHP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -Select-.
        '''</summary>
        Friend Shared ReadOnly Property Sel() As String
            Get
                Return ResourceManager.GetString("Sel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0.
        '''</summary>
        Friend Shared ReadOnly Property Sel1() As String
            Get
                Return ResourceManager.GetString("Sel1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to September.
        '''</summary>
        Friend Shared ReadOnly Property Sep() As String
            Get
                Return ResourceManager.GetString("Sep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 9.
        '''</summary>
        Friend Shared ReadOnly Property Sep1() As String
            Get
                Return ResourceManager.GetString("Sep1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Voting Day Monitoring System Mobile App.
        '''</summary>
        Friend Shared ReadOnly Property txtVDMS() As String
            Get
                Return ResourceManager.GetString("txtVDMS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Urban Local Body.
        '''</summary>
        Friend Shared ReadOnly Property Ulb() As String
            Get
                Return ResourceManager.GetString("Ulb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update.
        '''</summary>
        Friend Shared ReadOnly Property UpdateStockMaster() As String
            Get
                Return ResourceManager.GetString("UpdateStockMaster", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User Role:.
        '''</summary>
        Friend Shared ReadOnly Property userRole() As String
            Get
                Return ResourceManager.GetString("userRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Voting Day Monitoring System.
        '''</summary>
        Friend Shared ReadOnly Property VDMS() As String
            Get
                Return ResourceManager.GetString("VDMS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to View Annexure-I.
        '''</summary>
        Friend Shared ReadOnly Property ViewAnnexure() As String
            Get
                Return ResourceManager.GetString("ViewAnnexure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warehouse .
        '''</summary>
        Friend Shared ReadOnly Property Warehouse() As String
            Get
                Return ResourceManager.GetString("Warehouse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warehouse Location Not Found.
        '''</summary>
        Friend Shared ReadOnly Property WarehouseLocationNotFound() As String
            Get
                Return ResourceManager.GetString("WarehouseLocationNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Welcome.
        '''</summary>
        Friend Shared ReadOnly Property welcome() As String
            Get
                Return ResourceManager.GetString("welcome", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
